name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "amd64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build Docker image
        run: |
          docker buildx build \
          --platform=linux/amd64 \
          -t my-net7-app \
          --file TicTacToeServer/Dockerfile \
          --load \
          TicTacToeServer
        # --platform=linux/amd64 => wymuszamy x86_64
        # --load => wczytujemy obraz do lokalnego rejestru Docker w GitHub Actions

      # (Opcjonalnie) test uruchomienia kontenera
      - name: Test Docker container
        run: |
          docker run -d --name test-app -p 8080:8080 my-net7-app
          sleep 5
          docker ps
          # ewentualny curl:
          # curl http://localhost:8080
